package multiplex;

import javax.imageio.ImageIO;
import javax.swing.JDesktopPane;
import java.awt.image.BufferedImage;
import java.awt.*;
import java.io.*;
import javax.swing.JOptionPane;

public class admin_frame extends javax.swing.JFrame {

    /**
     * Creates new form nav_Frame
     */
    private BufferedImage img;
    public static JDesktopPane jdpDesktop;
    
    public admin_frame(login log)
    {
        log.setVisible(false);
        initComponents();
        this.setLocationRelativeTo(null);
        try
        {
            img = ImageIO.read(new File("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\MovieResevationSystem\\Multiplex\\src\\cloud.jpg"));
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }
        jdpDesktop = new JDesktopPane(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                double scaleFactor = Math.min(1d, getScaleFactorToFit(new Dimension(img.getWidth(), img.getHeight()), getSize()));
                int scaleWidth = (int) Math.round(img.getWidth() * scaleFactor);
                int scaleHeight = (int) Math.round(img.getHeight() * scaleFactor);
                Image scaled = img.getScaledInstance(scaleWidth, scaleHeight, Image.SCALE_SMOOTH);
                int width = getWidth() - 1;
                int height = getHeight() - 1;
                int x = (width - scaled.getWidth(this)) / 2;
                int y = (height - scaled.getHeight(this)) / 2;
                g.drawImage(scaled, x, y, this);
            }

            @Override
            public Dimension getPreferredSize() {
                return new Dimension(img.getWidth(), img.getHeight());
            }
        };
        this.setContentPane(jdpDesktop);
    }
    public double getScaleFactor(int iMasterSize, int iTargetSize)
    {
        double dScale = 1;
        if (iMasterSize > iTargetSize)
        {
            dScale = (double) iTargetSize / (double) iMasterSize;
        } 
        else
        {
            dScale = (double) iTargetSize / (double) iMasterSize;
        }
        return dScale;
    }
    public double getScaleFactorToFit(Dimension original, Dimension toFit)
    {
        double dScale = 1d;
        if (original != null && toFit != null)
        {
            double dScaleWidth = getScaleFactor(original.width, toFit.width);
            double dScaleHeight = getScaleFactor(original.height, toFit.height);
            dScale = Math.min(dScaleHeight, dScaleWidth);
        }
        return dScale;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        settingMenu = new javax.swing.JMenu();
        staffMenuItem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        addstaffMenuItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        customerDetailsMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        addMovieMenuItem = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        operationMenu = new javax.swing.JMenu();
        searchMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        pasteMenuItem = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java Multiplex - Ticket Reservation System");

        settingMenu.setMnemonic('s');
        settingMenu.setText("Menu");

        staffMenuItem.setMnemonic('t');
        staffMenuItem.setText("Staff Details");
        staffMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffMenuItemActionPerformed(evt);
            }
        });
        settingMenu.add(staffMenuItem);
        settingMenu.add(jSeparator4);

        addstaffMenuItem.setMnemonic('a');
        addstaffMenuItem.setText("Add Staff");
        addstaffMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstaffMenuItemActionPerformed(evt);
            }
        });
        settingMenu.add(addstaffMenuItem);
        settingMenu.add(jSeparator3);

        customerDetailsMenuItem.setMnemonic('c');
        customerDetailsMenuItem.setText("Customer Details");
        customerDetailsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerDetailsMenuItemActionPerformed(evt);
            }
        });
        settingMenu.add(customerDetailsMenuItem);
        settingMenu.add(jSeparator2);

        addMovieMenuItem.setMnemonic('f');
        addMovieMenuItem.setText("Add Movie");
        addMovieMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMovieMenuItemActionPerformed(evt);
            }
        });
        settingMenu.add(addMovieMenuItem);
        settingMenu.add(jSeparator5);

        jMenuItem1.setText("Delete Movie");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        settingMenu.add(jMenuItem1);

        menuBar.add(settingMenu);

        operationMenu.setMnemonic('o');
        operationMenu.setText("Booking");

        searchMenuItem.setMnemonic('r');
        searchMenuItem.setText("Search");
        searchMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMenuItemActionPerformed(evt);
            }
        });
        operationMenu.add(searchMenuItem);
        operationMenu.add(jSeparator1);

        pasteMenuItem.setMnemonic('u');
        pasteMenuItem.setText("Collection");
        pasteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteMenuItemActionPerformed(evt);
            }
        });
        operationMenu.add(pasteMenuItem);

        menuBar.add(operationMenu);

        exitMenu.setText("Exit");
        exitMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMenuMouseClicked(evt);
            }
        });
        menuBar.add(exitMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMovieMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMovieMenuItemActionPerformed
        add_movie mv = new add_movie(this);
        mv.setVisible(true);
    }//GEN-LAST:event_addMovieMenuItemActionPerformed

    private void searchMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMenuItemActionPerformed
        //jdpDesktop.remove(login.bookfrm);
        jdpDesktop.add(login.sf);
        login.sf.setVisible(true);
        //login.bookfrm.setVisible(false);
    }//GEN-LAST:event_searchMenuItemActionPerformed

    private void exitMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMenuMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMenuMouseClicked

    private void staffMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffMenuItemActionPerformed
        // TODO add your handling code here:
        staff_movie stff = new staff_movie(this);
        stff.setVisible(true);
    }//GEN-LAST:event_staffMenuItemActionPerformed

    private void customerDetailsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerDetailsMenuItemActionPerformed
        // TODO add your handling code here:
        cus_details cusd = new cus_details(this);
        cusd.setVisible(true);
    }//GEN-LAST:event_customerDetailsMenuItemActionPerformed

    private void addstaffMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstaffMenuItemActionPerformed
        // TODO add your handling code here:
        add_staff adstff = new add_staff(this);
        adstff.setVisible(true);
    }//GEN-LAST:event_addstaffMenuItemActionPerformed

    private void pasteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteMenuItemActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(this, "Under Construction!!!");
        collection c = new collection();
        c.setVisible(true);
        
    }//GEN-LAST:event_pasteMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        del_movie delmv = new del_movie();
        delmv.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addMovieMenuItem;
    private javax.swing.JMenuItem addstaffMenuItem;
    private javax.swing.JMenuItem customerDetailsMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu exitMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu operationMenu;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem searchMenuItem;
    private javax.swing.JMenu settingMenu;
    private javax.swing.JMenuItem staffMenuItem;
    // End of variables declaration//GEN-END:variables
}
